# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 'Humberto Pereira - a Machine Psychiatrist'
email: begnini@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Tentando entender o que se passa na cabeça dos computadores desde 1998.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.begnini.net" # the base hostname & protocol for your site
twitter_username: begnini
github_username:  begnini

# Build settings
markdown: kramdown
